name: build project
on: push
jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential devscripts debhelper clang-tidy
            
            - name: build
              run: make build
    test:
        runs-on: self-hosted
        needs: build

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Install build tools
              run: sudo apt-get update && sudo apt-get install -y build-essential
            
            - name: build and run test binary
              run: |
                make test
    lint:
        runs-on: self-hosted
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: tidy up
              run: |
                clang-tidy main.cpp -- -std=c++17
                clang-tidy rivers.cpp -- -std=c++17
    package:
        runs-on: self-hosted
        needs: [build, test]
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: rivers-pkg
                path: ../*.deb